name: Trigger auto deployment for oryxie

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/oryxie-AutoDeployTrigger-b9bdad06-c35d-474c-a008-c6236a611328.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ORYXIE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ORYXIE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ORYXIE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.ORYXIE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORYXIE_REGISTRY_PASSWORD }}
          containerAppName: oryxie
          resourceGroup: Oryxie
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


